name: captain_eco
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # state management
  flutter_bloc: ^8.1.5
  # Code generator
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  #  json_serializable: ^6.7.1
  #  json_annotation: ^4.8.1
  # Networking
  dio: ^5.4.3+1
  http: ^1.2.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  pretty_dio_logger: ^1.3.1

  intl: any
  easy_localization: ^3.0.7

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.10+1
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.0.0
  firebase_messaging: any
  fluttertoast: ^8.2.6
  flutter_secure_storage: ^9.2.2
  country_code_picker: ^3.0.0
  gap: ^3.0.1
  geolocator: ^12.0.0
  awesome_notifications: any
  cached_network_image: ^3.3.1
  # flutter_credit_card: ^4.0.1
  google_maps_flutter: ^2.7.0
  otp_text_field: ^1.1.3
  flutter_countdown_timer: ^4.1.0
  carousel_slider: ^4.2.1
  firebase_auth: ^5.0.0
  image_picker: ^1.1.2
  flutter_otp_text_field: ^1.1.3+2
  get: ^4.6.6
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  # flutter_dotenv: ^5.1.0
  form_field_validator: ^1.1.0
  icons_plus: ^5.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_datetime_picker_plus: ^2.2.0
  share_plus: ^9.0.0
  flutter_fortune_wheel: ^1.3.1
  slide_countdown: ^1.6.1
  easy_stepper: ^0.8.5
  primer_progress_bar: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/icon.png"
  adaptive_icon_foreground: "assets/app_icon/launcher_icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon/
    - assets/images/

